In [1]:
import axisrules as axis
import numpy as np
import itertools


In [18]:
rules = [axis.MinimalFlips, axis.BallotCompletion, axis.MinimalSwaps, axis.ForbiddenTriples]

def get_counter_example(rule, m, n):

    for _ in range(1000):
        votes = np.random.randint(0, 2, size=(n, m))
        best_axis = rule(votes).bruteforce()
        all_best_axis = [best_axis[i][0] for i in range(len(best_axis))]
        score = best_axis[0][1]
        best_axis_bis = rule(votes[:-1]).bruteforce()
        all_best_axis_bis = [best_axis_bis[i][0] for i in range(len(best_axis_bis))]
        score_bis = best_axis_bis[0][1]
        # print(rule(votes).get_score(best_axis),rule(votes).get_score(best_axis_bis),
            # rule(votes[:-1]).get_score(best_axis),rule(votes[:-1]).get_score(best_axis_bis))
        ok = True
        for axis in all_best_axis:
            if axis in all_best_axis_bis:
                ok = False

        if score_bis == 0 and len(best_axis_bis) == 1:
            ok = False

        if ok:
            print(votes)
            print(best_axis)
            print(best_axis_bis)
            for x in best_axis_bis:
                print(rule(votes).get_score(x[0]))
            break



In [29]:

m = 6
n = 4


get_counter_example(axis.MinimalFlips, m, n)

[[1 1 0 0 1 0]
 [1 1 1 0 1 0]
 [0 1 1 1 1 1]
 [1 1 0 1 0 1]]
[([2, 4, 0, 1, 5, 3], 1), ([2, 4, 0, 1, 3, 5], 1), ([2, 4, 1, 0, 5, 3], 1), ([2, 4, 1, 0, 3, 5], 1)]
[([0, 4, 1, 2, 5, 3], 0), ([0, 4, 1, 2, 3, 5], 0), ([0, 1, 4, 2, 5, 3], 0), ([0, 1, 4, 2, 3, 5], 0)]
2
2
2
2


In [50]:
axis.VoterDeletion(np.array([[1,1,1,1]])).bruteforce()

[([0, 1, 2, 3], 0)]